Adds TrafficControl and TrafficLegendControl
WiredSolutions/react-azure-maps pull request #91
Opened 2021-04-07 06:04 UTC by ambientlight

adds built-in TrafficControl and TrafficLegend control described in [Add Traffic Controls](https://docs.microsoft.com/en-us/azure////azure-maps/map-show-traffic#add-traffic-controls).

#### Additional Notes
There exist an issue for now in TrafficControl when `{isActive: true}` is passed inside `TrafficControlOptions` described at: [Traffic control option isActive doesn't work when control is added in map ready handler](https://docs.microsoft.com/en-us/answers/questions/347142/bug-report-traffic-control-option-isactive-doesn39.html)

2021-04-07 08:59 UTC, psrednicki approved these changes

2021-04-07 09:24 UTC, msasinowski requested changes

2021-04-07 09:24 UTC, msasinowski commented on src/components/AzureMap/useCreateMapControls.tsx
> +    case 'TrafficControl':
We should add, a test case for that

2021-04-09 19:11 UTC, ambientlight commented
@msasinowski: done, thanks

2021-04-11 13:23 UTC, psrednicki approved these changes
I included your changes in our playgroud controls example - https://github.com/WiredSolutions/react-azure-maps-playground/pull/48
Looks good! 🔥

2021-04-11 13:24 UTC, ambientlight commented
@psrednicki: great, thanks!

2021-04-11 14:25 UTC, msasinowski commented
@ambientlight I changed the circle ci build settings to allow run jobs from forks can you push a dummy commit so we can check it?

2021-04-11 14:29 UTC, msasinowski commented
@ambientlight We can also leave that mock with the class, we can use and mock this kind of thing as prototype and then even an instance of it. will work like that but in overall let's leave that. I think We are ready to merge, One more additional thing can you change the output from test coverage in the Readme file?  Anyway, I approve it and we are ready to go.

Good job and thanks for the contribution.

2021-04-11 14:29 UTC, msasinowski approved these changes

2021-04-11 14:33 UTC, ambientlight commented
@msasinowski: I think you are referring to vector tiles PR's? at https://github.com/WiredSolutions/react-azure-maps/blob/7dca5ed21aecc808b9a0247f7d556dafef3babcc/__mocks__/azure-maps-control.js#L1-L7

yeah sure, adding that here.

Thanks!

2021-04-11 14:35 UTC, msasinowski commented
> @msasinowski: I think you are referring to vector tiles PR's? at
> 
> https://github.com/WiredSolutions/react-azure-maps/blob/7dca5ed21aecc808b9a0247f7d556dafef3babcc/__mocks__/azure-maps-control.js#L1-L7
> 
> yeah sure, adding that here.
> 
> Thanks!

Yes, you are correct wrong browser tab, I also add this comment in the previous PR

2021-04-12 13:44 UTC, psrednicki approved these changes

2021-04-12 13:45 UTC, merged